# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableManager.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from ba2cc.ba2cc import BAManger, FileManager, DataManager, ExtremeManager


class Ui_tableManager(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        MainWindow.setBaseSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        self.menuCalculateBorder = QtWidgets.QMenu(self.menuAnalyze)
        self.menuCalculateBorder.setObjectName("menuCalculateBorder")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionAddRows = QtWidgets.QAction(MainWindow)
        self.actionAddRows.setObjectName("actionAddRows")
        self.actionAddColumns = QtWidgets.QAction(MainWindow)
        self.actionAddColumns.setObjectName("actionAddColumns")
        self.actionDeleteRows = QtWidgets.QAction(MainWindow)
        self.actionDeleteRows.setObjectName("actionDeleteRows")
        self.actionDeleteColumns = QtWidgets.QAction(MainWindow)
        self.actionDeleteColumns.setObjectName("actionDeleteColumns")
        self.actionDeleteAll = QtWidgets.QAction(MainWindow)
        self.actionDeleteAll.setObjectName("actionDeleteAll")
        self.actionDisplayDataDistributionChart = QtWidgets.QAction(MainWindow)
        self.actionDisplayDataDistributionChart.setObjectName("actionDisplayDataDistributionChart")
        self.actionDisplayBorderDistributionChart = QtWidgets.QAction(MainWindow)
        self.actionDisplayBorderDistributionChart.setObjectName("actionDisplayBorderDistributionChart")
        self.actionEntropyBorderAlgorithm = QtWidgets.QAction(MainWindow)
        self.actionEntropyBorderAlgorithm.setObjectName("actionEntropyBorderAlgorithm")
        self.actionSignedBorderAlgorithm = QtWidgets.QAction(MainWindow)
        self.actionSignedBorderAlgorithm.setObjectName("actionSignedBorderAlgorithm")
        self.actionUnsignedBorderAlgorithm = QtWidgets.QAction(MainWindow)
        self.actionUnsignedBorderAlgorithm.setObjectName("actionUnsignedBorderAlgorithm")
        self.actionSignedMeanBorderAlgorithm = QtWidgets.QAction(MainWindow)
        self.actionSignedMeanBorderAlgorithm.setObjectName("actionSignedMeanBorderAlgorithm")
        self.actionUnsignedMeanBorderAlgorithm = QtWidgets.QAction(MainWindow)
        self.actionUnsignedMeanBorderAlgorithm.setObjectName("actionUnsignedMeanBorderAlgorithm")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionUser_Option = QtWidgets.QAction(MainWindow)
        self.actionUser_Option.setObjectName("actionUser_Option")
        self.actionUserHelp = QtWidgets.QAction(MainWindow)
        self.actionUserHelp.setObjectName("actionUserHelp")
        self.actionLisence = QtWidgets.QAction(MainWindow)
        self.actionLisence.setObjectName("actionLisence")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuEdit.addAction(self.actionAddRows)
        self.menuEdit.addAction(self.actionAddColumns)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDeleteRows)
        self.menuEdit.addAction(self.actionDeleteColumns)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDeleteAll)
        self.menuCalculateBorder.addAction(self.actionEntropyBorderAlgorithm)
        self.menuCalculateBorder.addSeparator()
        self.menuCalculateBorder.addAction(self.actionSignedBorderAlgorithm)
        self.menuCalculateBorder.addAction(self.actionUnsignedBorderAlgorithm)
        self.menuCalculateBorder.addAction(self.actionSignedMeanBorderAlgorithm)
        self.menuCalculateBorder.addAction(self.actionUnsignedMeanBorderAlgorithm)
        self.menuAnalyze.addAction(self.actionDisplayDataDistributionChart)
        self.menuAnalyze.addAction(self.actionDisplayBorderDistributionChart)
        self.menuAnalyze.addSeparator()
        self.menuAnalyze.addAction(self.menuCalculateBorder.menuAction())
        self.menuOption.addAction(self.actionUser_Option)
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionUserHelp)
        self.menuOption.addAction(self.actionLisence)
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dato - Table Manager"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analyze"))
        self.menuCalculateBorder.setTitle(_translate("MainWindow", "Calculate Border"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionAddRows.setText(_translate("MainWindow", "Add Row"))
        self.actionAddColumns.setText(_translate("MainWindow", "Add Column"))
        self.actionDeleteRows.setText(_translate("MainWindow", "Delete Selected Row(s)"))
        self.actionDeleteColumns.setText(_translate("MainWindow", "Delete Selected Column(s)"))
        self.actionDeleteAll.setText(_translate("MainWindow", "Delete All"))
        self.actionDisplayDataDistributionChart.setText(_translate("MainWindow", "Display Data Distribution Chart"))
        self.actionDisplayBorderDistributionChart.setText(_translate("MainWindow", "Display Border Distribution Chart"))
        self.actionEntropyBorderAlgorithm.setText(_translate("MainWindow", "Entropy Border Algorithm"))
        self.actionSignedBorderAlgorithm.setText(_translate("MainWindow", "Signed Border Algorithm"))
        self.actionUnsignedBorderAlgorithm.setText(_translate("MainWindow", "Unsigned Border Algorithm"))
        self.actionSignedMeanBorderAlgorithm.setText(_translate("MainWindow", "Signed Mean Border Algorithm"))
        self.actionUnsignedMeanBorderAlgorithm.setText(_translate("MainWindow", "Unsigned Mean Border Algorithm"))
        self.actionLicense.setText(_translate("MainWindow", "License"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionUser_Option.setText(_translate("MainWindow", "User Option"))
        self.actionUser_Option.setShortcut(_translate("MainWindow", "Ctrl+Alt+O"))
        self.actionUserHelp.setText(_translate("MainWindow", "Help"))
        self.actionLisence.setText(_translate("MainWindow", "Lisence"))
        self.actionLisence.setShortcut(_translate("MainWindow", "Ctrl+Alt+L"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_tableManager()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
